# Site settings
title: Nathan Burleson dot com
description: A personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "choco" # the base hostname & protocol for your site
author: 
  name: Nate Burleson
  email: me+nbdotcom@nathanburleson.com

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Permalinks
permalink: /:categories/:year/:month/:day/:title.html

# Collections
collections:
  my_collection:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nathan Burleson"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  
# Pagination
paginate: 5
paginate_path: "/page:num/"

# Social Links (optional)
social_links:
  github: your_github_handle

# Optional settings
highlighter: rouge
