name: Upload To Azure
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: feeloor/azure-static-website-deploy@master
        env:
          SOURCE_DIR: "./public"
          AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
          AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
          AZURE_SECRET: ${{secrets.AZURE_SECRET}}
          AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          AZURE_STORAGE_ACCOUNT_NAME: ${{secrets.AZURE_STORAGE_ACCOUNT_NAME}}
          AZURE_INDEX_DOCUMENT_NAME: ${{secrets.AZURE_INDEX_DOCUMENT_NAME}}
          AZURE_ERROR_DOCUMENT_NAME: ${{secrets.AZURE_ERROR_DOCUMENT_NAME}}
